import type { Metadata } from "next";
import "../globals.css";

import Header from "@/components/Header";
import SideBar from "@/components/SideBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Timesheet AB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    <main className="flex flex-col h-dvh bg-gray-100 text-gray-800 overflow-y-hidden">
      {/* Header */}
      <div className="" style={{ height: "7dvh" }}>
        <Header />
      </div>

      {/* Main Content */}
      <div className="flex flex-1 " style={{ height: "90dvh" }}>
        {/* Sidebar */}
        <aside className="w-[10%]  bg-gray-800 text-white p-4">
          <SideBar />
        </aside>

        {/* Main Content Area */}
        <main className="flex-1 p-6  bg-white-900">{children}</main>
      </div>
    </main>
    // </html>
  );
}
