import type { Metadata } from "next";
import "./globals.css";
import { ContextProvider } from "@/context/ContextHook";

export const metadata: Metadata = {
  title: "Signup - Timesheet AB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-dvh ">
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
